/**
 * Fridge demo dataset.
 * Social metrics, promotions, and community activity are labelled DEMO DATA.
 * Swap `FridgeDataSource` for a verified TikTok / Instagram / promo API later.
 */
window.FridgeData = {
  meta: {
    generatedAt: '2026-09-22',
    socialDisclaimer: 'Demo data — not verified live TikTok or Instagram metrics.',
    promoDisclaimer: 'Sample offers — not connected to a verified promotion source.',
    rankingNote:
      'Rankings weight TikTok recency first, Instagram second. Google Reviews are not the primary signal.',
  },

  chips: [
    'Hawker Food',
    'Halal',
    'Muslim-Friendly',
    'Café',
    'Late-Night',
    'Fine Dining',
    'Budget Eats',
    'Vegetarian',
    'Desserts',
    'Seafood',
    'Korean',
    'Japanese',
    'Chinese',
    'Malay',
    'Indian',
    'Western',
  ],

  trendingSearches: [
    'halal supper',
    'Japanese omakase',
    'best kaya toast',
    'hidden cafés',
    'spicy food',
    'dessert near Bugis',
    'hawker chicken rice',
    'late night mala',
  ],

  eateries: [
    {
      id: 'tian-tian',
      name: 'Tian Tian Hainanese Chicken Rice',
      stallName: 'Tian Tian',
      hawkerCentre: 'Maxwell Food Centre',
      venueType: 'hawker',
      neighbourhood: 'Chinatown',
      lat: 1.2804,
      lng: 103.8448,
      signatureDish: 'Hainanese chicken rice',
      cuisine: 'Chinese',
      dishes: ['chicken rice', 'chicken soup'],
      pricePerPerson: 8,
      priceLabel: '$6–10',
      address: '1 Kadayanallur St, Maxwell Food Centre #01-10/11',
      hours: '11:00–20:00',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: ['muslim-friendly'],
      worthGoing: 3,
      tiktokHeat: 86,
      tiktokRecency: 'this-week',
      instagramPopularity: 78,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.6,
      whyTrending: 'Creators still queue for the silky poached chicken and ginger-chilli.',
      whyWorthGoing: 'Consistently excellent chicken rice at hawker prices — worth the wait if you like classics.',
      creators: ['@sghawkerwalks', '@eatwithmin'],
      tiktokActivity: '~42 creator mentions (demo, last 7 days)',
      instagramActivity: '~1.8k saves on recent Reels (demo)',
      sentiment: 'Queues are real, but flavour still matches the hype.',
      photo:
        'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'liao-fan',
      name: 'Hawker Chan Soya Sauce Chicken',
      stallName: 'Liao Fan Hawker Chan',
      hawkerCentre: 'Chinatown Complex',
      venueType: 'hawker',
      neighbourhood: 'Chinatown',
      lat: 1.2824,
      lng: 103.8436,
      signatureDish: 'Soya sauce chicken rice',
      cuisine: 'Chinese',
      dishes: ['soya sauce chicken', 'wanton noodles'],
      pricePerPerson: 7,
      priceLabel: '$5–9',
      address: '335 Smith St, Chinatown Complex #02-126',
      hours: '10:30–15:30',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 1,
      tiktokHeat: 92,
      tiktokRecency: 'this-week',
      instagramPopularity: 88,
      viral: true,
      tiktokLed: true,
      overhyped: true,
      communityScore: 3.4,
      whyTrending: 'Michelin-history clips keep going viral with 2-hour queue warnings.',
      whyWorthGoing: 'High visibility, mixed recent sentiment — visit only if you are already in Chinatown.',
      creators: ['@queuechronicles', '@sgfoodtok'],
      tiktokActivity: '~71 creator mentions (demo, last 7 days)',
      instagramActivity: 'Queue videos dominating Explore (demo)',
      sentiment: 'Overhype risk: long waits, inconsistent peak-hour plates.',
      photo:
        'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'tiong-bahru-bakery',
      name: 'Tiong Bahru Bakery',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Tiong Bahru',
      lat: 1.2856,
      lng: 103.8329,
      signatureDish: 'Kouign-amann & kopi',
      cuisine: 'Western',
      dishes: ['kaya toast', 'pastry', 'coffee'],
      pricePerPerson: 18,
      priceLabel: '$12–22',
      address: '56 Eng Hoon St, #01-01',
      hours: '08:00–18:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian-options'],
      worthGoing: 3,
      tiktokHeat: 74,
      tiktokRecency: 'classic',
      instagramPopularity: 90,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.5,
      whyTrending: 'Weekend pastry shots still land on Instagram; quieter weekday mornings.',
      whyWorthGoing: 'Buttery pastry and neighbourhood charm — a classic, not just a trend.',
      creators: ['@buttercrumbs', '@tbwalks'],
      tiktokActivity: '~18 mentions (demo, last 14 days)',
      instagramActivity: 'High café aesthetic saves (demo)',
      sentiment: 'Beloved classic; go early for kouign-amann.',
      photo:
        'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'nylon-coffee',
      name: 'Nylon Coffee Roasters',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Tiong Bahru',
      lat: 1.2768,
      lng: 103.8368,
      signatureDish: 'Single-origin pour-over',
      cuisine: 'Café',
      dishes: ['coffee', 'hidden cafés'],
      pricePerPerson: 10,
      priceLabel: '$6–14',
      address: '4 Everton Park, #01-40',
      hours: '08:30–17:30',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian-options'],
      worthGoing: 2,
      tiktokHeat: 41,
      tiktokRecency: 'classic',
      instagramPopularity: 62,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.4,
      whyTrending: 'Quiet specialty-coffee niche rather than mass viral clips.',
      whyWorthGoing: 'Hidden-gem energy: serious beans, tiny room, no circus queue.',
      creators: ['@thirdwavessg'],
      tiktokActivity: '~6 mentions (demo, last 30 days)',
      instagramActivity: 'Specialty coffee community posts (demo)',
      sentiment: 'For coffee people, not for spectacle.',
      photo:
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'song-fa',
      name: 'Song Fa Bak Kut Teh',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Bugis',
      lat: 1.2889,
      lng: 103.8492,
      signatureDish: 'Peppery bak kut teh',
      cuisine: 'Chinese',
      dishes: ['bak kut teh', 'you tiao'],
      pricePerPerson: 22,
      priceLabel: '$16–28',
      address: '11 New Bridge Rd',
      hours: '11:00–22:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['muslim-friendly'],
      worthGoing: 2,
      tiktokHeat: 63,
      tiktokRecency: 'recent',
      instagramPopularity: 70,
      viral: false,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.2,
      whyTrending: 'Late-lunch bak kut teh ASMR still circulating this month.',
      whyWorthGoing: 'Reliable pepper broth near Bugis — strong neighbourhood pick, not a spectacle.',
      creators: ['@souptoksg'],
      tiktokActivity: '~24 mentions (demo, last 14 days)',
      instagramActivity: 'Steady foodie tags (demo)',
      sentiment: 'Solid, slightly touristy, still a good bowl.',
      photo:
        'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'ah-chew',
      name: 'Ah Chew Desserts',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Bugis',
      lat: 1.2984,
      lng: 103.8556,
      signatureDish: 'Mango pomelo sago',
      cuisine: 'Chinese',
      dishes: ['dessert', 'tang yuan', 'mango sago'],
      pricePerPerson: 12,
      priceLabel: '$8–16',
      address: '1 Liang Seah St',
      hours: '12:30–23:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian-options'],
      worthGoing: 2,
      tiktokHeat: 81,
      tiktokRecency: 'this-week',
      instagramPopularity: 76,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.1,
      whyTrending: 'Dessert-near-Bugis searches spiked after night-out roundups.',
      whyWorthGoing: 'Late dessert that actually satisfies — mango sago is the move.',
      creators: ['@sweetteethsg', '@bugisbites'],
      tiktokActivity: '~38 mentions (demo, last 7 days)',
      instagramActivity: 'Night dessert carousels (demo)',
      sentiment: 'Busy but worth it for a sweet stop.',
      photo:
        'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'din-tai-fung',
      name: 'Din Tai Fung',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Orchard',
      lat: 1.3039,
      lng: 103.8318,
      signatureDish: 'Xiao long bao',
      cuisine: 'Chinese',
      dishes: ['xiao long bao', 'fried rice', 'noodles'],
      pricePerPerson: 38,
      priceLabel: '$28–48',
      address: 'Paragon, 290 Orchard Rd',
      hours: '11:00–21:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 55,
      tiktokRecency: 'classic',
      instagramPopularity: 72,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.3,
      whyTrending: 'Orchard lunch queues remain a staple on local food accounts.',
      whyWorthGoing: 'Consistent dumplings when you need a sure bet after shopping.',
      creators: ['@orchardbites'],
      tiktokActivity: '~11 mentions (demo, last 14 days)',
      instagramActivity: 'Family lunch posts (demo)',
      sentiment: 'Not exciting, very reliable.',
      photo:
        'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'sunday-folks',
      name: 'Sunday Folks',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Dempsey',
      lat: 1.3046,
      lng: 103.8102,
      signatureDish: 'Pots of gold soft serve',
      cuisine: 'Desserts',
      dishes: ['soft serve', 'dessert'],
      pricePerPerson: 16,
      priceLabel: '$10–20',
      address: 'Blk 17A Dempsey Rd',
      hours: '11:00–22:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian'],
      worthGoing: 3,
      tiktokHeat: 88,
      tiktokRecency: 'this-week',
      instagramPopularity: 93,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.4,
      whyTrending: 'Pistachio-on-gold-bowl clips exploded again this week.',
      whyWorthGoing: 'Playful dessert that still tastes as good as it photographs.',
      creators: ['@goldenscoop', '@dempseyeats'],
      tiktokActivity: '~54 mentions (demo, last 7 days)',
      instagramActivity: 'Very high aesthetic reach (demo)',
      sentiment: 'Viral and still delicious.',
      photo:
        'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'candlenut',
      name: 'Candlenut',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Dempsey',
      lat: 1.3054,
      lng: 103.8109,
      signatureDish: 'Buah keluak ayam',
      cuisine: 'Peranakan',
      dishes: ['peranakan', 'spicy food'],
      pricePerPerson: 85,
      priceLabel: '$70–110',
      address: '17A Dempsey Rd',
      hours: '12:00–15:00, 18:00–22:00',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 3,
      tiktokHeat: 48,
      tiktokRecency: 'classic',
      instagramPopularity: 68,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.7,
      whyTrending: 'Fine-dining Peranakan tasting clips circulate among food hosts.',
      whyWorthGoing: 'Uniqueness over virality — one of the most considered Peranakan tables in SG.',
      creators: ['@sgtables'],
      tiktokActivity: '~9 mentions (demo, last 30 days)',
      instagramActivity: 'Editorial restaurant posts (demo)',
      sentiment: 'Classic favourite, book ahead.',
      photo:
        'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'zam-zam',
      name: 'Zam Zam Restaurant',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Kampong Glam',
      lat: 1.3022,
      lng: 103.8588,
      signatureDish: 'Mutton murtabak',
      cuisine: 'Indian-Muslim',
      dishes: ['murtabak', 'nasi biryani', 'halal supper'],
      pricePerPerson: 16,
      priceLabel: '$10–22',
      address: '697–699 North Bridge Rd',
      hours: '07:00–23:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['halal', 'muslim-friendly'],
      worthGoing: 3,
      tiktokHeat: 79,
      tiktokRecency: 'this-week',
      instagramPopularity: 71,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.5,
      whyTrending: 'Halal supper roundups keep sending people to North Bridge Road.',
      whyWorthGoing: 'Flaky murtabak after midnight energy — a Kampong Glam essential.',
      creators: ['@halaleatsg', '@supperclubsg'],
      tiktokActivity: '~33 mentions (demo, last 7 days)',
      instagramActivity: 'Late-night food stories (demo)',
      sentiment: 'Packed, flavourful, still worth it.',
      photo:
        'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'hjh-maimunah',
      name: 'Hjh Maimunah',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Kampong Glam',
      lat: 1.3008,
      lng: 103.8596,
      signatureDish: 'Nasi padang spread',
      cuisine: 'Malay',
      dishes: ['nasi padang', 'rendang', 'sambal'],
      pricePerPerson: 18,
      priceLabel: '$12–24',
      address: '11 Jalan Pisang',
      hours: '07:00–21:00',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: ['halal', 'muslim-friendly'],
      worthGoing: 3,
      tiktokHeat: 67,
      tiktokRecency: 'recent',
      instagramPopularity: 64,
      viral: false,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.6,
      whyTrending: 'Home-style Malay buffet plates featured in “comfort food” TikToks.',
      whyWorthGoing: 'Generous nasi padang with soul — a first-stop for Malay classics.',
      creators: ['@makaneveryday'],
      tiktokActivity: '~21 mentions (demo, last 14 days)',
      instagramActivity: 'Family meal posts (demo)',
      sentiment: 'Warm, filling, highly recommended.',
      photo:
        'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'komala-vilas',
      name: 'Komala Vilas',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Little India',
      lat: 1.3067,
      lng: 103.8519,
      signatureDish: 'Masala thosai',
      cuisine: 'Indian',
      dishes: ['thosai', 'vegetarian', 'set meals'],
      pricePerPerson: 12,
      priceLabel: '$8–16',
      address: '76–78 Serangoon Rd',
      hours: '07:00–22:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian', 'halal'],
      worthGoing: 2,
      tiktokHeat: 52,
      tiktokRecency: 'classic',
      instagramPopularity: 58,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.3,
      whyTrending: 'Vegetarian travellers keep rediscovering banana-leaf thosai clips.',
      whyWorthGoing: 'Fast, cheap, fully vegetarian — strong if you want Indian comfort.',
      creators: ['@vegsg'],
      tiktokActivity: '~12 mentions (demo, last 14 days)',
      instagramActivity: 'Little India walking tours (demo)',
      sentiment: 'No-frills and dependable.',
      photo:
        'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'katong-laksa',
      name: '328 Katong Laksa',
      stallName: '328 Katong Laksa',
      hawkerCentre: null,
      venueType: 'hawker',
      neighbourhood: 'Katong',
      lat: 1.3051,
      lng: 103.9011,
      signatureDish: 'Katong laksa',
      cuisine: 'Peranakan',
      dishes: ['laksa', 'spicy food'],
      pricePerPerson: 9,
      priceLabel: '$7–11',
      address: '51 East Coast Rd',
      hours: '10:00–18:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['muslim-friendly'],
      worthGoing: 3,
      tiktokHeat: 77,
      tiktokRecency: 'this-week',
      instagramPopularity: 69,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.4,
      whyTrending: 'Cut-noodle laksa close-ups hit For You pages this week.',
      whyWorthGoing: 'Coconut-rich East Coast classic — spicy, slurpable, iconic.',
      creators: ['@eastcoastbites'],
      tiktokActivity: '~29 mentions (demo, last 7 days)',
      instagramActivity: 'Katong heritage reels (demo)',
      sentiment: 'Touristy but the bowl still slaps.',
      photo:
        'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'chin-mee-chin',
      name: 'Chin Mee Chin Confectionery',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Katong',
      lat: 1.3062,
      lng: 103.9046,
      signatureDish: 'Kaya toast & soft-boiled eggs',
      cuisine: 'Café',
      dishes: ['kaya toast', 'coffee', 'hidden cafés'],
      pricePerPerson: 8,
      priceLabel: '$5–12',
      address: '204 East Coast Rd',
      hours: '08:00–16:00',
      openDays: [2, 3, 4, 5, 6, 0],
      dietary: ['vegetarian-options'],
      worthGoing: 3,
      tiktokHeat: 71,
      tiktokRecency: 'recent',
      instagramPopularity: 80,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.5,
      whyTrending: '“Best kaya toast” videos revived this restored Peranakan bakery.',
      whyWorthGoing: 'Charcoal-toast nostalgia with a beautiful room — hidden-café mood, classic taste.',
      creators: ['@kayacrumbs', '@katongwalks'],
      tiktokActivity: '~27 mentions (demo, last 10 days)',
      instagramActivity: 'Heritage interior shots (demo)',
      sentiment: 'Go for breakfast; limited seats.',
      photo:
        'https://images.unsplash.com/photo-1482049016687-2d3ff1b12676?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'humpback',
      name: 'Humpback',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Joo Chiat',
      lat: 1.3134,
      lng: 103.9018,
      signatureDish: 'Grilled catch of the day',
      cuisine: 'Western',
      dishes: ['seafood', 'date night'],
      pricePerPerson: 55,
      priceLabel: '$40–70',
      address: '17 Joo Chiat Terrace',
      hours: '18:00–23:00',
      openDays: [2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 58,
      tiktokRecency: 'recent',
      instagramPopularity: 75,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.4,
      whyTrending: 'Joo Chiat date-night seafood plates circulating on Instagram more than TikTok.',
      whyWorthGoing: 'Neighbourhood seafood with atmosphere — worth considering for East Side nights.',
      creators: ['@joochiatnights'],
      tiktokActivity: '~14 mentions (demo, last 14 days)',
      instagramActivity: 'Date-night carousels (demo)',
      sentiment: 'Romantic, pricier, good for bookmarks.',
      photo:
        'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'ps-cafe',
      name: 'PS.Cafe Holland Village',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Holland Village',
      lat: 1.3109,
      lng: 103.7955,
      signatureDish: 'Truffle fries & all-day brunch',
      cuisine: 'Western',
      dishes: ['brunch', 'pasta'],
      pricePerPerson: 42,
      priceLabel: '$32–55',
      address: '273 Holland Ave',
      hours: '09:00–23:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian-options'],
      worthGoing: 2,
      tiktokHeat: 44,
      tiktokRecency: 'classic',
      instagramPopularity: 77,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.1,
      whyTrending: 'Holland V brunch staples rather than a new viral wave.',
      whyWorthGoing: 'Comfortable all-day café when you want a known quantity.',
      creators: ['@hollandvbites'],
      tiktokActivity: '~8 mentions (demo, last 21 days)',
      instagramActivity: 'Brunch flat-lays (demo)',
      sentiment: 'Pleasant, not a must if you dislike waits.',
      photo:
        'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'kko-kko',
      name: "Kko Kko Korean Fried Chicken",
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Holland Village',
      lat: 1.3116,
      lng: 103.7964,
      signatureDish: 'Yangnyeom fried chicken',
      cuisine: 'Korean',
      dishes: ['fried chicken', 'spicy food', 'soju'],
      pricePerPerson: 32,
      priceLabel: '$24–40',
      address: '31 Lorong Mambong',
      hours: '17:00–00:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 73,
      tiktokRecency: 'this-week',
      instagramPopularity: 66,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.2,
      whyTrending: 'Crunchy-chicken ASMR and late-night Holland V clips.',
      whyWorthGoing: 'Late-night Korean fried chicken with real crunch — good group food.',
      creators: ['@kkocrunch', '@nightowls'],
      tiktokActivity: '~31 mentions (demo, last 7 days)',
      instagramActivity: 'Group dinner stories (demo)',
      sentiment: 'Loud, fun, slightly greasy in the best way.',
      photo:
        'https://images.unsplash.com/photo-1498654896293-37bf4e8091c3?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'chomp-chomp',
      name: 'Chomp Chomp Satay',
      stallName: 'Chomp Chomp Satay',
      hawkerCentre: 'Chomp Chomp Food Centre',
      venueType: 'hawker',
      neighbourhood: 'Serangoon',
      lat: 1.3649,
      lng: 103.8665,
      signatureDish: 'Charcoal satay',
      cuisine: 'Malay',
      dishes: ['satay', 'late-night'],
      pricePerPerson: 14,
      priceLabel: '$8–18',
      address: '20 Kensington Park Rd',
      hours: '18:00–01:00',
      openDays: [2, 3, 4, 5, 6, 0],
      dietary: ['halal', 'muslim-friendly'],
      worthGoing: 3,
      tiktokHeat: 69,
      tiktokRecency: 'this-week',
      instagramPopularity: 61,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.5,
      whyTrending: 'Heartland supper satay smoke shots are trending among local creators.',
      whyWorthGoing: 'Night hawker energy — charcoal satay that beats many CBD options.',
      creators: ['@heartlandtok'],
      tiktokActivity: '~22 mentions (demo, last 7 days)',
      instagramActivity: 'Supper club tags (demo)',
      sentiment: 'Come hungry, stay late.',
      photo:
        'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'white-restaurant',
      name: 'White Restaurant',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Ang Mo Kio',
      lat: 1.3699,
      lng: 103.8484,
      signatureDish: 'Sang har mee',
      cuisine: 'Chinese',
      dishes: ['prawn noodles', 'big prawn'],
      pricePerPerson: 28,
      priceLabel: '$20–38',
      address: '53 Ang Mo Kio Ave 3, #B1-50/51 AMK Hub',
      hours: '11:00–21:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 46,
      tiktokRecency: 'classic',
      instagramPopularity: 50,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.2,
      whyTrending: 'Heartland prawn-noodle nostalgia more than a new wave.',
      whyWorthGoing: 'A strong AMK option if you want big prawns without going downtown.',
      creators: ['@northbites'],
      tiktokActivity: '~7 mentions (demo, last 21 days)',
      instagramActivity: 'Family lunch posts (demo)',
      sentiment: 'Local favourite, not a viral circus.',
      photo:
        'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'tampines-hokkien',
      name: 'No.18 Fried Hokkien Mee',
      stallName: 'No.18 Fried Hokkien Mee',
      hawkerCentre: 'Tampines Round Market & Food Centre',
      venueType: 'hawker',
      neighbourhood: 'Tampines',
      lat: 1.3454,
      lng: 103.9447,
      signatureDish: 'Fried Hokkien mee',
      cuisine: 'Chinese',
      dishes: ['hokkien mee', 'hawker'],
      pricePerPerson: 6,
      priceLabel: '$4–8',
      address: '137 Tampines St 11, Tampines Round Market',
      hours: '08:00–14:00',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 3,
      tiktokHeat: 64,
      tiktokRecency: 'recent',
      instagramPopularity: 45,
      viral: false,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.6,
      whyTrending: 'East-side hawker hunters keep filming the wok hei.',
      whyWorthGoing: 'Budget East Side stall with serious wok fragrance — hawker food done right.',
      creators: ['@tampineseats'],
      tiktokActivity: '~19 mentions (demo, last 14 days)',
      instagramActivity: 'Hawker close-ups (demo)',
      sentiment: 'Sold out by early afternoon.',
      photo:
        'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'jurong-nasi-lemak',
      name: 'Boon Lay Power Nasi Lemak',
      stallName: 'Boon Lay Power Nasi Lemak',
      hawkerCentre: 'Boon Lay Place Food Village',
      venueType: 'hawker',
      neighbourhood: 'Jurong East',
      lat: 1.3453,
      lng: 103.7128,
      signatureDish: 'Nasi lemak with spicy ikan billis',
      cuisine: 'Malay',
      dishes: ['nasi lemak', 'spicy food'],
      pricePerPerson: 6,
      priceLabel: '$4–9',
      address: '221 Boon Lay Place, Food Village',
      hours: '07:00–14:00',
      openDays: [1, 2, 3, 4, 5, 6, 0],
      dietary: ['halal', 'muslim-friendly'],
      worthGoing: 3,
      tiktokHeat: 82,
      tiktokRecency: 'this-week',
      instagramPopularity: 57,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.7,
      whyTrending: 'West-side nasi lemak pilgrimages went newly viral this week.',
      whyWorthGoing: 'Sambal with backbone and crispy ikan — worth the Jurong trip.',
      creators: ['@westsidewok', '@nasilemakclub'],
      tiktokActivity: '~36 mentions (demo, last 7 days)',
      instagramActivity: 'Queue photos from Boon Lay (demo)',
      sentiment: 'Long queue, food usually justifies it.',
      photo:
        'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'punggol-settlement',
      name: 'The Punggol Settlement Seafood',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Punggol',
      lat: 1.4208,
      lng: 103.9126,
      signatureDish: 'Chilli crab',
      cuisine: 'Seafood',
      dishes: ['chilli crab', 'cereal prawn', 'seafood'],
      pricePerPerson: 48,
      priceLabel: '$35–70',
      address: 'Punggol Settlement, 1 Punggol Timor',
      hours: '11:30–22:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['muslim-friendly'],
      worthGoing: 2,
      tiktokHeat: 76,
      tiktokRecency: 'newly-viral',
      instagramPopularity: 82,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.0,
      whyTrending: 'Waterfront chilli-crab sunset videos made Punggol newly viral.',
      whyWorthGoing: 'The view is half the dish — seafood is good, not the city’s best crab.',
      creators: ['@northcoastsg'],
      tiktokActivity: '~40 mentions (demo, last 7 days)',
      instagramActivity: 'Sunset dining reels (demo)',
      sentiment: 'Go for the vibe + crab combo.',
      photo:
        'https://images.unsplash.com/photo-1625944525533-473f1a3ed54b?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: false,
    },
    {
      id: 'woodlands-888',
      name: '888 Hokkien Prawn Mee',
      stallName: '888 Hokkien Prawn Mee',
      hawkerCentre: 'Woodlands Food Centre',
      venueType: 'hawker',
      neighbourhood: 'Woodlands',
      lat: 1.4363,
      lng: 103.7870,
      signatureDish: 'Hokkien prawn mee soup',
      cuisine: 'Chinese',
      dishes: ['prawn mee', 'hawker'],
      pricePerPerson: 6,
      priceLabel: '$4–8',
      address: 'Blk 4 Woodlands St 12, Woodlands Food Centre',
      hours: '08:00–15:00',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 39,
      tiktokRecency: 'classic',
      instagramPopularity: 33,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.3,
      whyTrending: 'North-side hawker roundups, not a national trend.',
      whyWorthGoing: 'If you are in Woodlands, this bowl is the convenient win.',
      creators: ['@northhawker'],
      tiktokActivity: '~5 mentions (demo, last 30 days)',
      instagramActivity: 'Local stall tags (demo)',
      sentiment: 'Quietly good heartland food.',
      photo:
        'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'lau-pa-sat',
      name: 'Lau Pa Sat Satay Street',
      stallName: 'Satay Street hawkers',
      hawkerCentre: 'Lau Pa Sat',
      venueType: 'hawker',
      neighbourhood: 'CBD',
      lat: 1.2807,
      lng: 103.8505,
      signatureDish: 'Boogie Street satay',
      cuisine: 'Malay',
      dishes: ['satay', 'late-night'],
      pricePerPerson: 18,
      priceLabel: '$12–25',
      address: '18 Raffles Quay, Satay Street',
      hours: '19:00–01:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['halal', 'muslim-friendly'],
      worthGoing: 2,
      tiktokHeat: 70,
      tiktokRecency: 'this-week',
      instagramPopularity: 84,
      viral: true,
      tiktokLed: true,
      overhyped: true,
      communityScore: 3.8,
      whyTrending: 'CBD after-work satay smoke is a weekly TikTok staple.',
      whyWorthGoing: 'Atmosphere-first. Satay is fine; expect tourist pricing.',
      creators: ['@cbdnights'],
      tiktokActivity: '~28 mentions (demo, last 7 days)',
      instagramActivity: 'Skyline + satay shots (demo)',
      sentiment: 'Fun with colleagues, not the city’s best satay.',
      photo:
        'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'a-noodle-story',
      name: 'A Noodle Story',
      stallName: 'A Noodle Story',
      hawkerCentre: 'Amoy Street Food Centre',
      venueType: 'hawker',
      neighbourhood: 'CBD',
      lat: 1.2793,
      lng: 103.8476,
      signatureDish: 'Modern dry laksa ramen',
      cuisine: 'Fusion',
      dishes: ['laksa', 'ramen', 'noodles'],
      pricePerPerson: 12,
      priceLabel: '$10–14',
      address: '7 Maxwell Rd, Amoy Street Food Centre #01-30',
      hours: '11:00–14:30, 17:30–21:00',
      openDays: [1, 2, 3, 4, 5],
      dietary: [],
      worthGoing: 3,
      tiktokHeat: 84,
      tiktokRecency: 'this-week',
      instagramPopularity: 73,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.5,
      whyTrending: 'Chef-hawker hybrid bowls keep landing on TikTok For You.',
      whyWorthGoing: 'Unique hawker craft — a modern classic that still feels special.',
      creators: ['@cbdbites', '@noodlelab'],
      tiktokActivity: '~47 mentions (demo, last 7 days)',
      instagramActivity: 'Chef-stall portraits (demo)',
      sentiment: 'Queue, but the bowl is distinctive.',
      photo:
        'https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'odette',
      name: 'Odette',
      stallName: null,
      hawkerCentre: null,
      venueType: 'fine-dining',
      neighbourhood: 'CBD',
      lat: 1.2897,
      lng: 103.8515,
      signatureDish: 'Seasonal tasting menu',
      cuisine: 'French',
      dishes: ['fine dining', 'tasting menu'],
      pricePerPerson: 380,
      priceLabel: '$280–450',
      address: 'National Gallery, 1 St Andrew’s Rd',
      hours: '12:00–13:30, 19:00–21:00',
      openDays: [2, 3, 4, 5, 6],
      dietary: ['vegetarian-options'],
      worthGoing: 3,
      tiktokHeat: 34,
      tiktokRecency: 'classic',
      instagramPopularity: 88,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.8,
      whyTrending: 'Special-occasion Instagram more than mass TikTok.',
      whyWorthGoing: 'A Singapore fine-dining landmark — uniqueness and craft, not a viral stunt.',
      creators: ['@sgtables'],
      tiktokActivity: '~4 mentions (demo, last 30 days)',
      instagramActivity: 'Tasting-menu editorials (demo)',
      sentiment: 'Classic favourite. Book months ahead.',
      photo:
        'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'burnt-ends',
      name: 'Burnt Ends',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Chinatown',
      lat: 1.2805,
      lng: 103.8416,
      signatureDish: 'Wood-fired beef short rib',
      cuisine: 'Western',
      dishes: ['bbq', 'steak', 'date night'],
      pricePerPerson: 160,
      priceLabel: '$120–200',
      address: '20 Teck Lim Rd',
      hours: '18:00–23:00',
      openDays: [2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 3,
      tiktokHeat: 61,
      tiktokRecency: 'recent',
      instagramPopularity: 86,
      viral: false,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.7,
      whyTrending: 'Fire-kitchen clips and counter seats still trend among food hosts.',
      whyWorthGoing: 'Smoke, precision, and a night-out that feels like a treat.',
      creators: ['@fireandfork'],
      tiktokActivity: '~16 mentions (demo, last 14 days)',
      instagramActivity: 'Chef-counter reels (demo)',
      sentiment: 'Pricey and worth it if you eat meat.',
      photo:
        'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'geylang-frog',
      name: 'Geylang Lor 9 Fresh Frog Porridge',
      stallName: null,
      hawkerCentre: null,
      venueType: 'restaurant',
      neighbourhood: 'Geylang',
      lat: 1.3138,
      lng: 103.8775,
      signatureDish: 'Ginger frog porridge',
      cuisine: 'Chinese',
      dishes: ['porridge', 'late-night', 'supper'],
      pricePerPerson: 20,
      priceLabel: '$14–28',
      address: '217 Geylang Rd',
      hours: '17:00–03:30',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 72,
      tiktokRecency: 'this-week',
      instagramPopularity: 60,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.1,
      whyTrending: 'Late-night Geylang supper vlogs spiked this week.',
      whyWorthGoing: 'A true supper institution — niche, fragrant, very Singapore.',
      creators: ['@supperclubsg'],
      tiktokActivity: '~26 mentions (demo, last 7 days)',
      instagramActivity: 'Night-market stories (demo)',
      sentiment: 'Not for everyone; loved by night owls.',
      photo:
        'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'newton',
      name: 'Newton Food Centre',
      stallName: 'Assorted Newton stalls',
      hawkerCentre: 'Newton Food Centre',
      venueType: 'hawker',
      neighbourhood: 'Newton',
      lat: 1.3119,
      lng: 103.8396,
      signatureDish: 'BBQ stingray & satay',
      cuisine: 'Hawker mix',
      dishes: ['stingray', 'satay', 'oyster omelette'],
      pricePerPerson: 22,
      priceLabel: '$15–35',
      address: '500 Clemenceau Ave North',
      hours: '12:00–02:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['muslim-friendly'],
      worthGoing: 1,
      tiktokHeat: 90,
      tiktokRecency: 'this-week',
      instagramPopularity: 85,
      viral: true,
      tiktokLed: true,
      overhyped: true,
      communityScore: 3.2,
      whyTrending: 'Tourist night-market videos never stop; “avoid the hard sell” warnings too.',
      whyWorthGoing: 'High TikTok heat, weaker value. Go only if you are nearby and curious.',
      creators: ['@touristtok', '@sgfoodwarn'],
      tiktokActivity: '~63 mentions (demo, last 7 days)',
      instagramActivity: 'Night hawker panoramas (demo)',
      sentiment: 'Viral but overhyped; watch prices.',
      photo:
        'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'sushi-tey',
      name: 'Sushi Kimura',
      stallName: null,
      hawkerCentre: null,
      venueType: 'fine-dining',
      neighbourhood: 'Orchard',
      lat: 1.3062,
      lng: 103.8296,
      signatureDish: 'Edo-style omakase',
      cuisine: 'Japanese',
      dishes: ['omakase', 'sushi', 'Japanese omakase'],
      pricePerPerson: 280,
      priceLabel: '$220–350',
      address: '333A Orchard Rd, #03-27 Mandarin Gallery',
      hours: '12:00–14:00, 18:00–22:00',
      openDays: [1, 2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 3,
      tiktokHeat: 57,
      tiktokRecency: 'recent',
      instagramPopularity: 74,
      viral: false,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.6,
      whyTrending: 'Omakase counter videos among SG food hosts this month.',
      whyWorthGoing: 'Focused Japanese omakase — worth it if that is what you are craving.',
      creators: ['@sushiclips'],
      tiktokActivity: '~13 mentions (demo, last 14 days)',
      instagramActivity: 'Nigiri close-ups (demo)',
      sentiment: 'Quiet excellence, limited seats.',
      photo:
        'https://images.unsplash.com/photo-1579871492000-04b215c8365d?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: false,
      newest: false,
    },
    {
      id: 'cloudstreet-new',
      name: 'Kaya Theory',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Joo Chiat',
      lat: 1.3148,
      lng: 103.8995,
      signatureDish: 'Brown-butter kaya toast set',
      cuisine: 'Café',
      dishes: ['kaya toast', 'coffee', 'hidden cafés'],
      pricePerPerson: 16,
      priceLabel: '$12–22',
      address: '112 Joo Chiat Rd',
      hours: '08:30–17:00',
      openDays: [0, 3, 4, 5, 6],
      dietary: ['vegetarian-options'],
      worthGoing: 2,
      tiktokHeat: 80,
      tiktokRecency: 'newly-viral',
      instagramPopularity: 79,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 4.0,
      whyTrending: 'Brand-new shophouse café; kaya-toast ASMR went newly viral.',
      whyWorthGoing: 'Fresh and pretty. Food is promising; still finding consistency.',
      creators: ['@newopengsg', '@kayacrumbs'],
      tiktokActivity: '~44 mentions (demo, last 7 days)',
      instagramActivity: 'Interior design reels (demo)',
      sentiment: 'Newly viral hidden café — go if you like first looks.',
      photo:
        'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: true,
    },
    {
      id: 'punggol-gelato',
      name: 'Tide & Toast',
      stallName: null,
      hawkerCentre: null,
      venueType: 'cafe',
      neighbourhood: 'Punggol',
      lat: 1.4054,
      lng: 103.9021,
      signatureDish: 'Sea-salt soft serve toast',
      cuisine: 'Desserts',
      dishes: ['dessert', 'toast', 'cafe'],
      pricePerPerson: 14,
      priceLabel: '$9–18',
      address: 'Waterway Point, 83 Punggol Central #01-21',
      hours: '10:00–22:00',
      openDays: [0, 1, 2, 3, 4, 5, 6],
      dietary: ['vegetarian'],
      worthGoing: 2,
      tiktokHeat: 75,
      tiktokRecency: 'newly-viral',
      instagramPopularity: 70,
      viral: true,
      tiktokLed: true,
      overhyped: false,
      communityScore: 3.9,
      whyTrending: 'New mall café with stretchy toast pulls all over TikTok.',
      whyWorthGoing: 'Fun North-side dessert; more viral than life-changing.',
      creators: ['@punggolfood'],
      tiktokActivity: '~35 mentions (demo, last 7 days)',
      instagramActivity: 'Toast-pull reels (demo)',
      sentiment: 'Cute, crowded on weekends.',
      photo:
        'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1200&q=80',
      lateNight: false,
      hasPromo: true,
      newest: true,
    },
    {
      id: 'bar-stories',
      name: 'Employees Only SG',
      stallName: null,
      hawkerCentre: null,
      venueType: 'bar',
      neighbourhood: 'Keong Saik',
      lat: 1.2798,
      lng: 103.8410,
      signatureDish: 'Late-night burgers & cocktails',
      cuisine: 'Western',
      dishes: ['cocktails', 'burger', 'late-night'],
      pricePerPerson: 45,
      priceLabel: '$30–60',
      address: '112 Amoy St',
      hours: '18:00–02:00',
      openDays: [2, 3, 4, 5, 6],
      dietary: [],
      worthGoing: 2,
      tiktokHeat: 50,
      tiktokRecency: 'recent',
      instagramPopularity: 72,
      viral: false,
      tiktokLed: false,
      overhyped: false,
      communityScore: 4.2,
      whyTrending: 'CBD-adjacent night-out posts rather than mass food virality.',
      whyWorthGoing: 'If you want a bar with actual food after 11pm.',
      creators: ['@sgbars'],
      tiktokActivity: '~10 mentions (demo, last 14 days)',
      instagramActivity: 'Nightlife posts (demo)',
      sentiment: 'Scene-y, decent burger.',
      photo:
        'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1200&q=80',
      lateNight: true,
      hasPromo: true,
      newest: false,
    },
  ],

  hotzones: [
    {
      id: 'hz-chinatown',
      name: 'Chinatown',
      label: 'Foodie hotspot',
      lat: 1.2815,
      lng: 103.8442,
      radius: 450,
      why: 'Hawker complexes plus chef-y Chinatown restaurants are stacked this week.',
      eateryIds: ['tian-tian', 'liao-fan', 'burnt-ends', 'a-noodle-story'],
    },
    {
      id: 'hz-joochiat',
      name: 'Joo Chiat / Katong',
      label: 'Trending this week',
      lat: 1.3105,
      lng: 103.902,
      radius: 550,
      why: 'Kaya toast, laksa, and new shophouse cafés are dominating East Side clips.',
      eateryIds: ['katong-laksa', 'chin-mee-chin', 'humpback', 'cloudstreet-new'],
    },
    {
      id: 'hz-kg',
      name: 'Kampong Glam',
      label: 'Trending this week',
      lat: 1.3016,
      lng: 103.8594,
      radius: 380,
      why: 'Halal supper and Malay comfort food searches are up after night-out roundups.',
      eateryIds: ['zam-zam', 'hjh-maimunah'],
    },
    {
      id: 'hz-punggol',
      name: 'Punggol',
      label: 'Newly viral',
      lat: 1.412,
      lng: 103.907,
      radius: 700,
      why: 'Waterfront seafood and a new toast café pushed the North into For You pages.',
      eateryIds: ['punggol-settlement', 'punggol-gelato'],
    },
    {
      id: 'hz-tiong',
      name: 'Tiong Bahru',
      label: 'Foodie hotspot',
      lat: 1.2838,
      lng: 103.8335,
      radius: 420,
      why: 'Café heritage strip remains a weekend hotspot for pastry and coffee.',
      eateryIds: ['tiong-bahru-bakery', 'nylon-coffee'],
    },
  ],

  promotions: [
    {
      id: 'p1',
      eateryId: 'ah-chew',
      restaurant: 'Ah Chew Desserts',
      offer: '2-for-1 mango pomelo sago after 9pm',
      type: '2-for-1',
      terms: 'Dine-in only. Cheaper item waived. Demo offer.',
      dates: '22 Sep 2026 – 12 Oct 2026',
      location: 'Bugis',
    },
    {
      id: 'p2',
      eateryId: 'din-tai-fung',
      restaurant: 'Din Tai Fung',
      offer: 'Weekday set lunch $32++',
      type: 'set meal',
      terms: 'Mon–Fri 11:00–15:00. Demo offer.',
      dates: '1 Sep 2026 – 30 Sep 2026',
      location: 'Orchard',
    },
    {
      id: 'p3',
      eateryId: 'hjh-maimunah',
      restaurant: 'Hjh Maimunah',
      offer: 'Student 15% off nasi padang',
      type: 'student',
      terms: 'Valid student pass. Demo offer.',
      dates: 'All of Sep 2026',
      location: 'Kampong Glam',
    },
    {
      id: 'p4',
      eateryId: 'ps-cafe',
      restaurant: 'PS.Cafe',
      offer: 'DBS/POSB 20% off selected mains',
      type: 'bank-card',
      terms: 'Min spend $50. One card per table. Demo offer.',
      dates: '15 Sep 2026 – 15 Oct 2026',
      location: 'Holland Village',
    },
    {
      id: 'p5',
      eateryId: 'bar-stories',
      restaurant: 'Employees Only SG',
      offer: 'Happy hour cocktails 2-for-1',
      type: 'happy-hour',
      terms: '18:00–20:00 Tue–Fri. Demo offer.',
      dates: 'Through Oct 2026',
      location: 'Keong Saik',
    },
    {
      id: 'p6',
      eateryId: 'cloudstreet-new',
      restaurant: 'Kaya Theory',
      offer: 'Opening month: complimentary egg on kaya sets',
      type: 'limited-time',
      terms: 'While stocks last before 11am. Demo offer.',
      dates: '18 Sep 2026 – 18 Oct 2026',
      location: 'Joo Chiat',
    },
    {
      id: 'p7',
      eateryId: 'kko-kko',
      restaurant: 'Kko Kko',
      offer: 'Weekday 2-for-1 fried chicken wings',
      type: '2-for-1',
      terms: 'Dine-in before 19:00. Demo offer.',
      dates: 'Sep 2026',
      location: 'Holland Village',
    },
    {
      id: 'p8',
      eateryId: 'punggol-settlement',
      restaurant: 'Punggol Settlement Seafood',
      offer: 'Weekday chilli crab set for 2 at $88',
      type: 'set meal',
      terms: 'Mon–Thu lunch. Demo offer.',
      dates: '1 Sep 2026 – 31 Oct 2026',
      location: 'Punggol',
    },
    {
      id: 'p9',
      eateryId: 'tiong-bahru-bakery',
      restaurant: 'Tiong Bahru Bakery',
      offer: 'Coffee + pastry weekday combo $9',
      type: 'set meal',
      terms: 'Takeaway 8–11am. Demo offer.',
      dates: 'Sep 2026',
      location: 'Tiong Bahru',
    },
    {
      id: 'p10',
      eateryId: 'white-restaurant',
      restaurant: 'White Restaurant',
      offer: 'UOB card $10 off $60',
      type: 'bank-card',
      terms: 'AMK Hub outlet. Demo offer.',
      dates: 'Now – 30 Sep 2026',
      location: 'Ang Mo Kio',
    },
  ],

  newestStores: [
    {
      id: 'n1',
      eateryId: 'cloudstreet-new',
      opened: '12 Sep 2026',
      blurb: 'Joo Chiat shophouse café dedicated to brown-butter kaya.',
    },
    {
      id: 'n2',
      eateryId: 'punggol-gelato',
      opened: '5 Sep 2026',
      blurb: 'Waterway Point toast café with sea-salt soft serve.',
    },
  ],

  foodies: [
    {
      id: 'f1',
      name: 'Aisha R.',
      handle: '@aisheats',
      avatar: 'AR',
      neighbourhood: 'Kampong Glam',
      bio: 'Halal supper hunter.',
    },
    {
      id: 'f2',
      name: 'Marcus T.',
      handle: '@wokhei',
      avatar: 'MT',
      neighbourhood: 'Tampines',
      bio: 'Hawker purist. East Side.',
    },
    {
      id: 'f3',
      name: 'Elaine K.',
      handle: '@cafeshelf',
      avatar: 'EK',
      neighbourhood: 'Tiong Bahru',
      bio: 'Pastry and quiet corners.',
    },
    {
      id: 'f4',
      name: 'Hafiz N.',
      handle: '@nightmakan',
      avatar: 'HN',
      neighbourhood: 'Woodlands',
      bio: 'Late-night heartland food.',
    },
    {
      id: 'f5',
      name: 'Priya S.',
      handle: '@spicefirst',
      avatar: 'PS',
      neighbourhood: 'Little India',
      bio: 'Vegetarian + chilli.',
    },
  ],

  visits: [
    {
      id: 'v1',
      foodieId: 'f1',
      eateryId: 'zam-zam',
      rating: 3,
      date: '20 Sep 2026',
      dish: 'Mutton murtabak',
      review: 'Flaky, filling, still the supper move.',
      visibility: 'public',
    },
    {
      id: 'v2',
      foodieId: 'f2',
      eateryId: 'tampines-hokkien',
      rating: 3,
      date: '19 Sep 2026',
      dish: 'Fried Hokkien mee',
      review: 'Wok hei before 11am. Don’t come late.',
      visibility: 'public',
    },
    {
      id: 'v3',
      foodieId: 'f3',
      eateryId: 'tiong-bahru-bakery',
      rating: 3,
      date: '21 Sep 2026',
      dish: 'Kouign-amann',
      review: 'Weekday morning = no circus.',
      visibility: 'public',
    },
    {
      id: 'v4',
      foodieId: 'f4',
      eateryId: 'chomp-chomp',
      rating: 3,
      date: '18 Sep 2026',
      dish: 'Satay',
      review: 'Smoke in the hair, worth it.',
      visibility: 'public',
    },
    {
      id: 'v5',
      foodieId: 'f5',
      eateryId: 'komala-vilas',
      rating: 2,
      date: '17 Sep 2026',
      dish: 'Masala thosai',
      review: 'Fast, cheap, always on.',
      visibility: 'public',
    },
    {
      id: 'v6',
      foodieId: 'f1',
      eateryId: 'hjh-maimunah',
      rating: 3,
      date: '16 Sep 2026',
      dish: 'Rendang',
      review: 'Took two friends who “don’t have a dinner plan”.',
      visibility: 'public',
    },
    {
      id: 'v7',
      foodieId: 'f3',
      eateryId: 'cloudstreet-new',
      rating: 2,
      date: '22 Sep 2026',
      dish: 'Kaya toast',
      review: 'Pretty room. Kaya is rich. Still finding its feet.',
      visibility: 'public',
    },
    {
      id: 'v8',
      foodieId: 'f2',
      eateryId: 'newton',
      rating: 1,
      date: '15 Sep 2026',
      dish: 'Stingray',
      review: 'Viral, overpriced. Convenient only.',
      visibility: 'public',
    },
  ],

  groups: [
    {
      id: 'g1',
      name: 'Friday supper (join if free)',
      topic: 'Late-night makan for people without a group chat',
      members: 18,
      messages: [
        { from: 'Aisha', text: 'Zam Zam at 10:30? Halal, easy MRT.' },
        { from: 'Hafiz', text: 'If too packed we fallback to Chomp Chomp satay.' },
        { from: 'Fridge', text: 'This is a demo group. Create your own anytime.' },
      ],
    },
    {
      id: 'g2',
      name: 'East Side kaya crawl',
      topic: 'Katong + Joo Chiat pastries',
      members: 9,
      messages: [
        { from: 'Elaine', text: 'Chin Mee Chin at 9, then Kaya Theory.' },
        { from: 'Marcus', text: 'Laksa after if we still have stomachs.' },
      ],
    },
  ],
};

window.FridgeDataSource = {
  async getAll() {
    return window.FridgeData;
  },
};
